### PR TITLE
customer data app first version

### PR DESCRIPTION
**Pull request by tgberkeley**

### CODE REVIEW

**Review by martinxu9 — COMMENTED** [review]
Is this app ready for review? Or you plan to come back to it later @tgberkeley

**Comment by Alek99** [comment]
Screenshot 2024-04-02 at 3 57 36 PM

The modal stays white in dark mode 
Screenshot 2024-04-02 at 3 57 56 PM

Also on a smaller screen size it doesn't center correctly

**Comment by tgberkeley** [comment]
Created an issue for the light and dark mode issue

**Review by Alek99 — APPROVED** [review]

**Comment by masenf** [comment]
why did we merge with broken CI?

**Pull request merged**
